version: '3.8'

services:
  health-checker:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./config.json:/app/config.json:ro
      - ./email_config.json:/app/email_config.json:ro
      - ./servers.json:/app/servers.json:ro
    restart: always  