version: '3.8'

services:
  postgres:
    image: postgres:14
    environment: 
      POSTGRES_DB: checker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d checker -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - app-network

  health-checker:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./config.json:/app/config.json:ro
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
