FROM golang:1.23-alpine 

ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64 \
    GOPROXY=https://proxy.golang.org,direct

WORKDIR /usr/src/app

COPY go.mod go.sum ./

RUN go mod download

COPY . .
    
RUN go build -o main ./cmd/main.go

CMD ["./main"]