x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:

  database:
    image: postgres:alpine
    restart: ${POSTGRES_RESTART_POLICY}
    container_name: ${PROJECT_NAME}-database
    logging: *default-logging
    ports:  
      - "3040:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ${PROJECT_ROOT}/database:/database
      - /etc/localtime:/etc/localtime:ro  
      - /etc/timezone:/etc/timezone:ro  

  backend:
    build:
      context: ${PROJECT_ROOT}
      dockerfile: ${PROJECT_ROOT}/docker/Dockerfile
    restart: ${APP_RESTART_POLICY}
    ports:
      - ${APP_PORT}:${APP_PORT}
    logging: *default-logging
    environment:
      POSTGRES_HOST: database
    depends_on:
      - database
    volumes:
      - ${PROJECT_ROOT}/logs:/usr/src/app/logs
      - ${PROJECT_ROOT}/.env:/usr/src/app/.env
      - /etc/localtime:/etc/localtime:ro 
      - /etc/timezone:/etc/timezone:ro
    stop_signal: SIGTERM
    stop_grace_period: 20s
    command: [ "./main" ]


volumes:
  postgres_data: