definitions:
  entities.Error:
    properties:
      loc:
        items:
          type: string
        type: array
      msg:
        type: string
      type:
        type: string
    type: object
  requests.CreateReceiver:
    properties:
      email:
        type: string
    type: object
  requests.CreateServer:
    properties:
      name:
        type: string
      url:
        type: string
    type: object
  requests.UpdateBasic:
    properties:
      checkIntervalInSeconds:
        type: integer
      notificationIntervalInHours:
        type: integer
      timeoutInSeconds:
        type: integer
    type: object
  responses.CreateReceiver:
    properties:
      id:
        type: integer
    type: object
  responses.CreateServer:
    properties:
      id:
        type: integer
    type: object
  responses.GetBasicConfig:
    properties:
      checkIntervalInSeconds:
        type: integer
      notificationIntervalInHours:
        type: integer
      timeoutInSeconds:
        type: integer
    type: object
  responses.GetReceivers:
    properties:
      email:
        type: string
      id:
        type: integer
      muted:
        type: boolean
    type: object
  responses.GetServer:
    properties:
      id:
        type: integer
      name:
        type: string
      url:
        type: string
    type: object
info:
  contact: {}
  description: API for managing servers
  title: Health Checker API
  version: "1.0"
paths:
  /api/v0/basic:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/responses.GetBasicConfig'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.Error'
      summary: Get all basic configs
      tags:
      - basic_config
    put:
      description: 'Update necessary configs: check_interval, timeout and notification
        interval'
      parameters:
      - description: Basic Config
        in: body
        name: basic_config
        required: true
        schema:
          $ref: '#/definitions/requests.UpdateBasic'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.Error'
      summary: Update basic config
      tags:
      - basic_config
  /api/v0/receiver:
    delete:
      description: Delete Receiver
      parameters:
      - description: Receiver ID
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Success
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.Error'
      summary: Delete Receiver
      tags:
      - receivers
    get:
      description: Retrieve a list of all receivers
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/responses.GetReceivers'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.Error'
      summary: Get all receivers
      tags:
      - receivers
    post:
      description: Create a receiver
      parameters:
      - description: Receiver Email
        in: body
        name: receiver_email
        required: true
        schema:
          $ref: '#/definitions/requests.CreateReceiver'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/responses.CreateReceiver'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.Error'
      summary: Create a receiver
      tags:
      - receivers
  /api/v0/receiver/mute:
    get:
      description: Mute a receiver
      parameters:
      - description: Receiver Email
        in: query
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Receiver muted successfully
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/entities.Error'
      summary: Mute Receiver
      tags:
      - receivers
  /api/v0/receiver/unmute:
    get:
      description: Unmute a receiver
      parameters:
      - description: Receiver Email
        in: query
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Receiver unmuted successfully
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entities.Error'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/entities.Error'
      summary: Unmute Receiver
      tags:
      - receivers
  /api/v0/servers:
    delete:
      description: Delete Server
      parameters:
      - description: Server ID
        in: query
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: Success
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.Error'
      summary: Delete Server
      tags:
      - servers
    get:
      description: Retrieve a list of all servers
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/responses.GetServer'
              type: array
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.Error'
      summary: Get All Servers
      tags:
      - servers
    post:
      description: Create Server
      parameters:
      - description: Server Details
        in: body
        name: server_details
        required: true
        schema:
          $ref: '#/definitions/requests.CreateServer'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            $ref: '#/definitions/responses.CreateServer'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.Error'
      summary: Create Server
      tags:
      - servers
swagger: "2.0"
